name: 'Setup Environment'
description: 'Setup Node.js and install dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
